#
# This file contains configuration flags to customize your site
#

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Name of your site (displayed in the header)
name: WAPRO
signin-link: false
# Short bio or description (displayed in the header)
description: "Web & App Professionals"

# URL of your avatar or profile pic (you could use your GitHub profile pic)
#avatar: https://avatars2.githubusercontent.com/u/10619762?v=3&s=200
avatar: /images/WAPRO.png
#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: wapro@MediaDoneRight.com
  facebook: groups/uncodedlb
  flickr:
  github: uncodedlb
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: waprolb
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"

irc:
  channels: uncodedlb
  nick: wapro

twitter:
  highlight: '<!--blockquote class="twitter-tweet" data-conversation="none" lang="en"><p><a href="https://twitter.com/hashtag/Uncoded?src=hash">#Uncoded</a> is happening!&#10;&#10;APR 16 <a href="http://t.co/tPFCHRtWM3">http://t.co/tPFCHRtWM3</a>&#10;&#10;<a href="https://twitter.com/hashtag/WAPRO?src=hash">#WAPRO</a> <a href="https://twitter.com/activelamp">@activelamp</a> <a href="https://twitter.com/schmittyjd">@schmittyjd</a> <a href="https://twitter.com/rogerhoward">@rogerhoward</a> <a href="https://twitter.com/btmash">@btmash</a> <a href="http://t.co/M2ijIYoMo5">pic.twitter.com/M2ijIYoMo5</a></p>&mdash; Mike Stewart (@MediaDoneRight) <a href="https://twitter.com/MediaDoneRight/status/587790944751104000">April 14, 2015</a></blockquote-->'
# Repository Path
repository: "https://github.com/uncodedlb/waprolb/tree/gh-pages/_posts/"

# Your disqus shortname, entering this will enable commenting on posts
disqus: wapro

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-60220524-5


# WAPRO data

sponsors:
  food:
    name: Beacon Hill
    logo: "" #"/images/logos/beaconhill.png"
    twitter: "BHStaffingGroup"
    desc: "Beacon Hill Technologies, the technology specialty division of Beacon Hill Staffing Group, is a national IT staffing organization that operates across industries and provides contract, direct (permanent), consulting and project management services to top companies and their IT departments."
    extra: ""
  venues:
    gj:
      short: "GJ" # WELABS || GJ
      name: "Gunn|Jerkens"
      image: "/images/GunnJerkins-Offices.jpg"
      logo: "/images/logos/gj.jpg"
      twitter: "gunnjerkens"
      desc: "Gunn | Jerkens, we've got a passion for creating new innovative marketing, branding and interactive web based solutions for our growing client base."
      extra: ""
    welabs:
      short: "WELABS" # WELABS || GJ
      name: "WE Labs"
      logo: ""
      image: ""
      twitter: "_WELABS"
      desc: "WE LABS is awesome coworking in Long Beach"
      extra: ""
  prize:
    pearson:
      name: "Pearson | Peachpit | InformIT"
      image: ""
      logo: "/images/logos/pearson-peachpit-informit.png"
      twitter: "informit"
      desc: "**PEARSON:** Helping to build a better world through education. **PEACHPIT:** Peachpit offers unique learning experiences in photography, graphic design, Web design & development, & more.  **InformIT:** is home to the world's leading technology publishers."
      extra: "Prizes are provided to *WAPRO* free of charge as an opportunity for our members to sample thier quality learning materials and in the process for the publisher to improve their materials.  To do this, all they ask in return is for our winners to please share a review.  Good examples of reviews can be found [here](http://www.amazon.com/review/R1YE2E39KV55DM/ref=cm_cr_rdp_perm?ie=UTF8&ASIN=0735683204), [here](http://www.amazon.com/review/R38DIMKQM0HR4A/ref=cm_cr_rdp_perm?ie=UTF8&ASIN=0133892387) and [here](http://www.amazon.com/review/R173FKSQ80UWS2/ref=cm_cr_rdp_perm). **Note:** Pearson is looking for open, honest and constructive reviews. If you dig the title, cool. If you don't dig it, also cool. Honesty and constructive feedback is what matters. Please send a link of the review using [contact info](/contact/) so it can be documented, possibly shared by uncoded.org, and help us maintain relations to obtain future prizes"



#
# !! You don't need to change any of the configuration flags below !!
#
base:
  twitter: "https://twitter.com/"
  fb: "https://facebook.com/"
#markdown: redcarpet
highlighter: rouge
permalink: /:categories/:year/:month/

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-redirect-from # 301 redirects - https://help.github.com/articles/redirects-on-github-pages/

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
